spring.application.name=hospital-ms

#server.port=9090

#MySql
spring.datasource.url=jdbc:mysql://localhost:3306/hospital
spring.datasource.username=root
spring.datasource.password=nn0itr@.

# Kafka Configuration
spring.kafka.bootstrap-servers=localhost:9092

kafka.topic.timer-info=timer-info-topic