spring.application.name=hospital-ms

#server.port=9090

#MySql
spring.datasource.url=jdbc:mysql://localhost:3306/hospital
spring.datasource.username=root
spring.datasource.password=nn0itr@.

# Kafka Configuration
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer= org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer= org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.consumer.properties.spring.json.trusted.packages=com.nnoi.core.kafka.model
spring.kafka.producer.properties.spring.json.type.mapping=abstractMessage:com.nnoi.core.kafka.model.AbstractMessage,customMessage:com.nnoi.core.kafka.model.CustomMessage,timerInfoMessage:com.nnoi.core.kafka.model.TimerInfoMessage
#spring.kafka.producer.properties.spring.json.add.type.headers=true  # default is true
kafka.topic.timer-info=timer-info-topic